home_index:
    path: /home/index
    host: localhost
    defaults:
        _controller: Home
        _action: index

home_hello:
    path: /home/hello/{name}
    host: "{host}.{domain}"
    defaults:
        _controller: Home
        _action: hello
        domain: dev
    requirements:
        domain: dev|loc

api_user_get:
    path: /api/users/get
    defaults:
        _controller: ApiUsers
        _action: get

api_admin:
    path: /api/admin
    defaults:
        _controller: ApiUsers
        _action: admin

api_test_get:
    path: /api/test/get
    defaults:
        _controller: ApiTest
        _action: get

login:
    path: /login
    defaults:
        _controller: Login
        _action: login

login_check:
    path: /login_check
    defaults:
        _controller: Login
        _action: loginCheck

logout:
    path: /logout
    defaults:
        _controller: Login
        _action: logout