home_index:
    path: /home/index
    host: localhost
    defaults:
        _controller: Home
        _action: index

home_hello:
    path: /home/hello/{name}
    host: "{host}.{domain}"
    defaults:
        _controller: Home
        _action: hello
        domain: dev
    requirements:
        domain: dev|loc

api_user_get:
    path: /api/users/get
    defaults:
        _controller: ApiUsers
        _action: get

api_admin:
    path: /api/admin
    defaults:
        _controller: ApiUsers
        _action: admin