#imports:
#    - { resource: /home/dima/Develop/symfony-certification-prepare-project/src/Resources/config/service_parameters.xml }

parameters:
    delegating_serializer.class: DG\SymfonyCert\Service\Serializer\DelegatingSerializer
    array_logger.class: DG\SymfonyCert\Service\Logger\ArrayLogger
    api.makes.class: DG\SymfonyCert\Service\EdmundsApi\MakesService
    api.makes.factory.class: DG\SymfonyCert\Service\EdmundsApi\MakesServiceFactory

    api.models.class: DG\SymfonyCert\Service\EdmundsApi\ModelsService

    api.calls.statistics.class: DG\SymfonyCert\Service\ServiceCallsStatistics

    json_to_array.serializer.class: DG\SymfonyCert\Service\Serializer\JsonToArraySerializer
    json_to_stdClass.serializer.class: DG\SymfonyCert\Service\Serializer\JsonToArraySerializer

services:
    delegating_serializer:
        lazy: true
        class: %delegating_serializer.class%

    json_to_array.serializer:
        class: %json_to_array.serializer.class%
        tags:
            - {name: serializer, format: 'json_to_array'}

    json_to_stdClass.serializer:
        class: %json_to_stdClass.serializer.class%
        tags:
            - {name: serializer, format: 'json_to_stdClass'}

    array_logger:
        class: %array_logger.class%

    api.base:
        abstract: true
        class: DG\SymfonyCert\Service\EdmundsApi\BaseApiService
        configurator: [DG\SymfonyCert\Service\ApiServiceConfigurator, configure]
        calls:
            - [setLogger, [@array_logger]]
            - [setDispatcher, [@event_dispatcher.traceable]]

    api.makes:
        public: true
        class: %api.makes.class%
        parent: api.base
        arguments: [%api.endpoint%, %api.key%, @delegating_serializer]

    api.models:
        class: %api.models.class%
        parent: api.base
        arguments: [%api.endpoint%, %api.key%, @delegating_serializer]
        calls:
            - [setDispatcher, [@event_dispatcher]]
        tags:
            - {name: kernel.event_listener, event: makes.cache.complete, method: onMakesCache}

    api.calls.statistics:
        class: %api.calls.statistics.class%
        tags:
            - {name: kernel.event_subscriber}

    logger.configurator:
        public: false
        class: DG\SymfonyCert\Service\EdmundsApi\LoggerConfigurator
        arguments: [@array_logger]

    log.conf:
        alias: logger.configurator

    event_dispatcher.traceable:
        class: Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher
        factory: [@event_dispatcher.traceable.factory, create]

    event_dispatcher.traceable.factory:
        class: DG\SymfonyCert\Service\TraceableEventDispatcherFactory
        arguments: [@event_dispatcher]

    csrf_token.manager:
        class: Symfony\Component\Security\Csrf\CsrfTokenManager

    translator:
        class: Symfony\Component\Translation\Translator
        synthetic: true

    url_generator:
        class: Symfony\Component\Routing\Generator\UrlGenerator
        synthetic: true
